platform :ios, '12.0'

target 'ExampleApp' do
  use_frameworks!
  pod 'RxSwift',    '~> 4.0'
  pod 'RxCocoa',    '~> 4.0'
  pod 'Alamofire'
  pod 'SwiftKeychainWrapper'
  pod 'OHHTTPStubs/Swift', '~> 9.1.0'

  target 'ExampleAppTests' do
    pod 'Behave', :path => '..'
    inherit! :search_paths
  end
end
