language: swift
osx_image: xcode12.0

before_install:
- brew update
- brew outdated xctool || brew upgrade xctool
- gem install xcpretty -N


script:
  - xctool -project Behave.xcworkspace   -scheme "Behave" -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 7" ONLY_ACTIVE_ARCH=NO test | xcpretty -c
