language: swift
osx_image: xcode12.0

before_install:
- brew update
- brew outdated xctool || brew upgrade xctool
- gem install xcpretty -N


script:
  - xcodebuild test -workspace Behave.xcworkspace -scheme "Behave" COMPILER_INDEX_STORE_ENABLE=NO -destination 'platform=iOS Simulator,OS=12.2,name=iPhone 8'| tee xcodebuild.log | xcpretty
