language: swift
osx_image: xcode12.0

before_install:
- brew update
- brew outdated xctool || brew upgrade xctool
- gem install xcpretty -N


script:
  - xcodebuild clean test -project Behave.xcodeproj -scheme Behave -destination "platform=iOS Simulator,name=iPhone 7,OS=12.2" ONLY_ACTIVE_ARCH=NO -quiet | xcpretty -c
