language: swift

osx_image: xcode12.0
env:
  matrix:
    - TEST_SDK=iphonesimulator12.1 OS=12.1 NAME='iPhone XR'
    - TEST_SDK=iphonesimulator12.1 OS=12.1 NAME='iPhone 7'

script:
  - set -o pipefail && xcodebuild test -enableCodeCoverage YES -project Behave.xcworkspace -scheme Behave -destination "platform=iOS Simulator,OS=12.2 ONLY_ACTIVE_ARCH=YES