language: swift
osx_image: xcode11.6

before_install:
- brew update
- gem install bundler
- brew outdated xctool || brew upgrade xctool
- gem install xcpretty -N

cache:
  directories:
    - "$HOME/Library/Caches/Homebrew"
    - "$HOME/.cache/Homebrew"
deploy:
  provider: script
  script: bash run-tests.sh

before_cache:
    - brew cleanup -s
