# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

target 'ExampleSwiftUI' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ExampleSwiftUI

  target 'ExampleSwiftUITests' do
    inherit! :search_paths
    pod 'ViewInspector'
    # Pods for testing
  end

  target 'ExampleSwiftUIUITests' do
    # Pods for testing
  end

end
